/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MigrationsNewRouteImport } from './routes/migrations/new'
import { Route as MigrationsIdIndexRouteImport } from './routes/migrations/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsNewRoute = MigrationsNewRouteImport.update({
  id: '/migrations/new',
  path: '/migrations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsIdIndexRoute = MigrationsIdIndexRouteImport.update({
  id: '/migrations/$id/',
  path: '/migrations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/migrations/new': typeof MigrationsNewRoute
  '/migrations/$id/': typeof MigrationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/migrations/new': typeof MigrationsNewRoute
  '/migrations/$id': typeof MigrationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/migrations/new': typeof MigrationsNewRoute
  '/migrations/$id/': typeof MigrationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/migrations/new' | '/migrations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/migrations/new' | '/migrations/$id'
  id: '__root__' | '/' | '/migrations/new' | '/migrations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MigrationsNewRoute: typeof MigrationsNewRoute
  MigrationsIdIndexRoute: typeof MigrationsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations/new': {
      id: '/migrations/new'
      path: '/migrations/new'
      fullPath: '/migrations/new'
      preLoaderRoute: typeof MigrationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations/$id/': {
      id: '/migrations/$id/'
      path: '/migrations/$id'
      fullPath: '/migrations/$id/'
      preLoaderRoute: typeof MigrationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MigrationsNewRoute: MigrationsNewRoute,
  MigrationsIdIndexRoute: MigrationsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
